In [1]:
from src.cnc import CNC, simulate_from_distribution
from src.utils import Pauli #, qutip_simuation
from src.vertex_decomposition import find_vertex_decomposition, find_cnc_vertex_decomposition

#### Simulation Example

In [20]:
num_simulations = 2048
cnc_set = { Pauli("II"),
    Pauli("IZ"),
    Pauli("ZI"),
    Pauli("ZZ"),
    Pauli("YI"),
    Pauli("YZ"),
    Pauli("XI"),
    Pauli("XZ"),
}

value_assignment1 = {pauli: 0 for pauli in cnc_set}

cnc_1  = CNC(value_assignment1)

value_assignment2 = {
    Pauli("II"): 0,
    Pauli("IZ"): 0,
    Pauli("ZI"): 0,
    Pauli("ZZ"): 0,
    Pauli("YI"): 1,
    Pauli("YZ"): 1,
    Pauli("XI"): 1,
    Pauli("XZ"): 1,
}

cnc3 = CNC({
    Pauli("II"): 0,
    Pauli("IZ"): 0,
    Pauli("ZI"): 0,
    Pauli("ZZ"): 0,
})

cnc_2 = CNC(value_assignment2)

measurements = [
    Pauli("YY"),
    Pauli("ZI"),
]

distribution = {cnc3: 1}

counts_cnc = simulate_from_distribution(
    distribution, measurements, num_simulations
)

In [3]:
counts_cnc

{'00': 519, '01': 530, '10': 491, '11': 508}

In [4]:
#from qutip import Qobj, identity, sigmaz, sigmay, tensor

#II = tensor(identity(2), identity(2))
#ZI = tensor(sigmaz(), identity(2))
#IZ = tensor(identity(2), sigmaz())
#ZZ = tensor(sigmaz(), sigmaz())
#YY = tensor(sigmay(), sigmay())

#rho = 1 / 4 * (II + ZI + IZ + ZZ)
#
#measurements = [YY, ZI]
#
#num_simulations = 2048
#counts_qutip = qutip_simuation(rho, measurements, num_simulations)

In [5]:
#counts_qutip

#### Finding initial distribution

In [6]:
from src.utils import load_all_maximal_cncs_matrix

all_cncs_2 = load_all_maximal_cncs_matrix(2)
all_cncs_3 = load_all_maximal_cncs_matrix(3)

In [7]:
all_cncs_1 = load_all_maximal_cncs_matrix(1)

In [8]:
all_cncs_1.shape

(4, 14)

In [9]:
all_cncs_2.shape

(16, 492)

In [10]:
all_cncs_2

array([[ 1,  1,  1, ...,  1,  1,  1],
       [ 0, -1,  0, ...,  1,  0,  0],
       [ 0,  0,  0, ...,  0,  0, -1],
       ...,
       [-1,  0,  0, ...,  0, -1, -1],
       [-1,  1,  0, ...,  0,  0,  0],
       [ 0, -1,  0, ...,  0,  0, -1]])

In [11]:
all_cncs_3.shape

(64, 72216)

Check whether pauli basis representation functions work as intended.

In [12]:
print(all_cncs_2[:, 0])
cnc = CNC.from_pauli_basis_representation(all_cncs_2[:, 0])
print(cnc.gamma)
cnc.get_pauli_basis_representation()

[ 1  0  0 -1  0 -1  1  0 -1  0  0  1  0 -1 -1  0]
{Pauli Operator: II: 0, Pauli Operator: IZ: 1, Pauli Operator: XX: 1, Pauli Operator: XY: 0, Pauli Operator: YI: 1, Pauli Operator: YZ: 0, Pauli Operator: ZX: 1, Pauli Operator: ZY: 1}


array([ 1,  0,  0, -1,  0, -1,  1,  0, -1,  0,  0,  1,  0, -1, -1,  0])

In [13]:
import numpy as np
initial_state = np.zeros(16)
initial_state[0] = 1

Find initial distribution

In [14]:
is_convex, distribution = find_vertex_decomposition(initial_state, all_cncs_2)

Welcome to the CBC MILP Solver 
Version: 2.10.3 
Build Date: Dec 15 2019 

command line - /Users/selmanipek/GitHub/PolytopeSimulation/venv/lib/python3.12/site-packages/pulp/solverdir/cbc/osx/64/cbc /var/folders/m4/pp85n2_d0t35q9wcrh9x24fr0000gn/T/19f03aebde0242ed988c15ab4a4a82fa-pulp.mps -timeMode elapsed -branch -printingOptions all -solution /var/folders/m4/pp85n2_d0t35q9wcrh9x24fr0000gn/T/19f03aebde0242ed988c15ab4a4a82fa-pulp.sol (default strategy 1)
At line 2 NAME          MODEL
At line 3 ROWS
At line 22 COLUMNS
At line 3828 RHS
At line 3846 BOUNDS
At line 3848 ENDATA
Problem MODEL has 17 rows, 493 columns and 3804 elements
Coin0008I MODEL read with 0 errors
Option for timeMode changed from cpu to elapsed
Presolve 16 (-1) rows, 492 (-1) columns and 3312 (-492) elements
0  Obj 0 Primal inf 0.999999 (1) Dual inf 491.99951 (492)
12  Obj 0
Optimal - objective value 0
After Postsolve, objective 0, infeasibilities - dual 0 (0), primal 0 (0)
Optimal objective 0 - 12 iterations time 0.002,

In [15]:
is_convex

True

In [16]:
for decomp_element in distribution:
    print(decomp_element)

DecompositionElement(operator=array([ 1, -1, -1, -1, -1,  1,  1,  1,  0,  0,  0,  0,  0,  0,  0,  0]), probability=0.11111111)
DecompositionElement(operator=array([ 1,  0,  0, -1,  0, -1,  1,  0,  0, -1, -1,  0,  1,  0,  0, -1]), probability=0.11111111)
DecompositionElement(operator=array([ 1, -1,  0,  0,  1, -1,  0,  0, -1,  1,  0,  0, -1,  1,  0,  0]), probability=0.055555556)
DecompositionElement(operator=array([ 1,  1, -1,  0,  0,  0,  0, -1,  0,  0,  0,  1,  0,  0,  0,  1]), probability=0.11111111)
DecompositionElement(operator=array([ 1,  0,  0,  0,  0, -1, -1, -1,  1,  0,  0,  0, -1,  0,  0,  0]), probability=0.055555556)
DecompositionElement(operator=array([ 1,  0,  1,  1,  0,  1,  0,  0,  0,  1,  0,  0,  0, -1,  0,  0]), probability=0.11111111)
DecompositionElement(operator=array([ 1,  0,  1,  0, -1,  0, -1,  0,  0,  0,  0,  0,  0,  0,  0,  0]), probability=0.11111111)
DecompositionElement(operator=array([ 1,  1,  1, -1,  0,  0,  0,  0,  1,  1,  1, -1,  0,  0,  0,  0]), probab

In [17]:
result_vec = np.zeros(16)
for i, decomp_element in enumerate(distribution):
    op = decomp_element.operator
    prob = decomp_element.probability
    result_vec += prob * op

result_vec

array([ 9.99999996e-01,  6.93889390e-18,  1.99999999e-09,  2.00000001e-09,
        2.00000001e-09, -2.00000000e-09, -1.38777878e-17,  0.00000000e+00,
        0.00000000e+00,  0.00000000e+00,  2.00000000e-09, -2.00000000e-09,
       -2.00000000e-09,  2.00000000e-09,  0.00000000e+00,  0.00000000e+00])

In [18]:
is_convex, distribution = find_cnc_vertex_decomposition(initial_state)

Welcome to the CBC MILP Solver 
Version: 2.10.3 
Build Date: Dec 15 2019 

command line - /Users/selmanipek/GitHub/PolytopeSimulation/venv/lib/python3.12/site-packages/pulp/solverdir/cbc/osx/64/cbc /var/folders/m4/pp85n2_d0t35q9wcrh9x24fr0000gn/T/80b54fe60eb843559980b738adf9360f-pulp.mps -timeMode elapsed -branch -printingOptions all -solution /var/folders/m4/pp85n2_d0t35q9wcrh9x24fr0000gn/T/80b54fe60eb843559980b738adf9360f-pulp.sol (default strategy 1)
At line 2 NAME          MODEL
At line 3 ROWS
At line 22 COLUMNS
At line 3828 RHS
At line 3846 BOUNDS
At line 3848 ENDATA
Problem MODEL has 17 rows, 493 columns and 3804 elements
Coin0008I MODEL read with 0 errors
Option for timeMode changed from cpu to elapsed
Presolve 16 (-1) rows, 492 (-1) columns and 3312 (-492) elements
0  Obj 0 Primal inf 0.999999 (1) Dual inf 491.99951 (492)
12  Obj 0
Optimal - objective value 0
After Postsolve, objective 0, infeasibilities - dual 0 (0), primal 0 (0)
Optimal objective 0 - 12 iterations time 0.002,

In [19]:
for i, decomp_element in enumerate(distribution):
    cnc = decomp_element.operator
    prob = decomp_element.probability
    print(f"CNC {i}: with probability {prob}")
    for pauli, value in cnc.gamma.items():
        print(f"{pauli}: {value}")

CNC 0: with probability 0.11111111
Pauli Operator: II: 0
Pauli Operator: IX: 1
Pauli Operator: IY: 1
Pauli Operator: IZ: 1
Pauli Operator: XI: 1
Pauli Operator: XX: 0
Pauli Operator: XY: 0
Pauli Operator: XZ: 0
CNC 1: with probability 0.11111111
Pauli Operator: II: 0
Pauli Operator: IZ: 1
Pauli Operator: XX: 1
Pauli Operator: XY: 0
Pauli Operator: YX: 1
Pauli Operator: YY: 1
Pauli Operator: ZI: 0
Pauli Operator: ZZ: 1
CNC 2: with probability 0.055555556
Pauli Operator: II: 0
Pauli Operator: IX: 1
Pauli Operator: XI: 0
Pauli Operator: XX: 1
Pauli Operator: YI: 1
Pauli Operator: YX: 0
Pauli Operator: ZI: 1
Pauli Operator: ZX: 0
CNC 3: with probability 0.11111111
Pauli Operator: II: 0
Pauli Operator: IX: 0
Pauli Operator: IY: 1
Pauli Operator: XZ: 1
Pauli Operator: YZ: 0
Pauli Operator: ZZ: 0
CNC 4: with probability 0.055555556
Pauli Operator: II: 0
Pauli Operator: XX: 1
Pauli Operator: XY: 1
Pauli Operator: XZ: 1
Pauli Operator: YI: 0
Pauli Operator: ZI: 1
CNC 5: with probability 0.11111